pub use crate::prelude::*;

/// Details about an override. Last write wins.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct Override {
    /// override request id for an override request
    #[serde(rename = "requestId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// proto field path which is the string representation of a field.
    /// example: correlated.primary_entity_id would be primary_entity_id in correlated component
    #[serde(rename = "fieldPath")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field_path: Option<String>,
    /// new field value corresponding to field path. In the shape of an empty entity with only the changed value.
    /// example: entity: { mil_view: { disposition: Disposition_DISPOSITION_HOSTILE } }
    #[serde(rename = "maskedFieldValue")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub masked_field_value: Option<Box<Entity>>,
    /// status of the override
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OverrideStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provenance: Option<Provenance>,
    /// The type of the override, defined by the stage of the entity lifecycle that the entity was in when the override
    /// was requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#type: Option<OverrideType>,
    /// Timestamp of the override request. The timestamp is generated by the Entity Manager instance that receives the request.
    #[serde(rename = "requestTimestamp")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::offset::option")]
    pub request_timestamp: Option<DateTime<FixedOffset>>,
}

impl Override {
    pub fn builder() -> OverrideBuilder {
        <OverrideBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct OverrideBuilder {
    request_id: Option<String>,
    field_path: Option<String>,
    masked_field_value: Option<Box<Entity>>,
    status: Option<OverrideStatus>,
    provenance: Option<Provenance>,
    r#type: Option<OverrideType>,
    request_timestamp: Option<DateTime<FixedOffset>>,
}

impl OverrideBuilder {
    pub fn request_id(mut self, value: impl Into<String>) -> Self {
        self.request_id = Some(value.into());
        self
    }

    pub fn field_path(mut self, value: impl Into<String>) -> Self {
        self.field_path = Some(value.into());
        self
    }

    pub fn masked_field_value(mut self, value: Box<Entity>) -> Self {
        self.masked_field_value = Some(value);
        self
    }

    pub fn status(mut self, value: OverrideStatus) -> Self {
        self.status = Some(value);
        self
    }

    pub fn provenance(mut self, value: Provenance) -> Self {
        self.provenance = Some(value);
        self
    }

    pub fn r#type(mut self, value: OverrideType) -> Self {
        self.r#type = Some(value);
        self
    }

    pub fn request_timestamp(mut self, value: DateTime<FixedOffset>) -> Self {
        self.request_timestamp = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`Override`].
    pub fn build(self) -> Result<Override, BuildError> {
        Ok(Override {
            request_id: self.request_id,
            field_path: self.field_path,
            masked_field_value: self.masked_field_value,
            status: self.status,
            provenance: self.provenance,
            r#type: self.r#type,
            request_timestamp: self.request_timestamp,
        })
    }
}
